### ISSUE TITLE
Suggestion: Add some collaborators for PRs

### ISSUE THREAD

**Issue by morajabi** [iliakan/javascript-tutorial-en#109]
It's just a suggestion based on what I saw during this month. I saw so many simple PRs which fix a typo waited almost weeks to merge. 
I think adding some active collaborators if you're busy most of the time should be a useful thing because most of PRs are just fixing typos. For start I want to be one if you wish.
And I must thank you @iliakan for all your amazing works on this 👍

**Comment by iliakan** [comment]
Right now there's 1 open issue and 1 open PR (changes requested).

Looks like I'm able to handle that? :)

**Comment by iliakan** [comment]
P.S. Thank you, I would accept collaborators who can add something worthy to the tutorial.

**Comment by morajabi** [comment]
Yes today, but sometimes I’ve seen senarios like I said :) OK. I don’t think I’m that professional to add something to tutorials that much but I think I can handle PRs if you weren’t around.

**Comment by iliakan** [comment]
Thanks, I don't see a lot of hanging PR now :).
