### ISSUE TITLE
Suggestion: export as epub/mobi

### ISSUE THREAD

**Issue by tobiasger** [iliakan/javascript-tutorial-en#119]
I think it would be great if the tutorial could be exported in the **epub** or **mobi** format through the website. Has there been any attempts or thoughts about doing this earlier?

**Comment by iliakan** [comment]
Yeah, but for epub - not all readers understand the HTML-EPUB conversion made by Calibre.

**Comment by GeorgySerga** [comment]
Would also love to have epub version. Is there any kind of version just to test? I tried myself to create one directly, but it looks like css modifying is required, content column is too narrow in the book.

**Comment by Bludkey** [comment]
Or if it could be exported in any other book/document format eg. PDF, .doc
I would like to read it as a book (on Kindle).

**Comment by iliakan** [comment]
Actually fixed (epub/pdf exists)
