### ISSUE TITLE
Offering to copyedit entire tutorial

### ISSUE THREAD

**Issue by jmbothe** [iliakan/javascript-tutorial-en#124]
@iliakan thanks for accepting my recent grammar/usage/punctuation pull request. If you'd like, I could review and edit the entire tutorial. With the little time I have available outside of work, I could probably complete the task in about four weeks. I just wanted to check with you to make sure this is something you are looking for, before I commit to the task. I suspect that this is something you'd be open to, considering the header on the tutorial pages explicitly requesting help with editing :)

I am a newbie coder just looking to get involved in a project somehow. As I mentioned in my pull request, my focus would **only** be grammar, word usage, and punctuation. I wouldn't be editing any sections of code (unless I was very confident an error existed), and I wouldn't seek to edit any of the text's style or meaning.

Let me know what you think. Cheers!

**Comment by iliakan** [comment]
@jmbothe that'd be great, feel free to suggest changes that include readability as well.
I'll review all changes to make sure they are technically correct.

Please make PRs as you go, don't smack me with one huge 4-week PR.

**Comment by jmbothe** [comment]
Cool! Thanks for the opportunity. A question about PR size/frequency: what is the ideal size of a PR, and how often could I submit? For example, my last PR included three articles. Should PR request be smaller? Could they be larger? 

To meet my goal of finishing in one month, I would have to edit about four articles a day. So that would be one PR per day with four articles, or three PRs per week with twelve articles each, or one PR per week with twenty eight articles... you get the idea. Of course that's assuming that there will be edits for each article, which might not be the case. If that's too much I could also extend the timeline to six weeks or two months.

**Comment by iliakan** [comment]
Per-article PR seems sane.

**Comment by iliakan** [comment]
P.S. When I read the tutorial myself, I always note many places where I could say the same in more elegant and interesting way.

**Comment by iliakan** [comment]
@jmbothe could you please look at the two new PRs from @gwooly?

I have many doubts about them, and not enough proficiency to decide are the changes right.

**Comment by iliakan** [comment]
Closing, as nothing is being done AFAIK. Thank you guys!
