### ISSUE TITLE
In section: "Classes" after subsection: "Getters/setters" in line 5 of code

### ISSUE THREAD

**Issue by Annis-Monadjem** [iliakan/javascript-tutorial-en#128]
In the `constructor` change ` this._name = name;` into ` this.name = name;` or as it is the code will not do what it is intended to do.

The final code should be:
<pre>
class User {
  constructor(value) {
    // invokes the setter
    this.name = value;
  }

  get name() {
    return this._name;
  }

  set name(value) {
    if (value.length < 4) {
      alert("Name too short.");
      return;
    }
    this._name = value;
  }
}
</pre>

**Comment by iliakan** [comment]
Maybe suggest a PR? You can edit the article in github pretty easily! :)

**Comment by iliakan** [comment]
And your contribution will be well-written in the history of the tutorial.

**Comment by Annis-Monadjem** [comment]
I'm new to programming. If I'm understanding you correctly, you are saying that i should close this comment/issue and manually copy it into pull requests. I'll be opening a PR first time. Should i open an PR by forking this project or in any other way? please explain.
