### ISSUE TITLE
More A Question Than An Issue Really - An Observation To Be Correctly - Iliakan, Please Explain

### ISSUE THREAD

**Issue by Annis-Monadjem** [iliakan/javascript-tutorial-en#135]
@iliakan thanks for creating this site; it is really helpful to my learning js.
 
I'm not able to use Disqus comments at `javascript.info` and so I'm placing here mostly a question (it might turn out into an issue or perhaps a PR if you decide so which I'm not sure how to handle yet; my apologies). I'm really trying to understand the tutorial and 'playing around' with the code to grasp it. So please let me know how you want me to place future questions of this sort on `javascript-tutorial-en`.

So here is my question: 
In the `Drag'n'Drop with mouse events` section in the very first and in the very last examples the code includes this one:
<pre>
...
document.body.append(ball);
...
</pre>

It seems to me that this line is redundant. After all `ball` is the id to one of the only two div's and so it is already part of the `body` hence it does not need any further `append`ing. In my editor when I remove the above line i do not observe any difference in drag-n-drop behaviour of the ball. Let me know if I am not understanding anything. Thanks.

**Comment by iliakan** [comment]
The ball may be somewhere else, positioned relative to other elements.
