### ISSUE TITLE
'Edit on Github' in new tab?

### ISSUE THREAD

**Issue by Kurczok** [iliakan/javascript-tutorial-en#163]
More of a suggestion than an issue but wouldn't it be more intuitive to have Github open in a new tab to edit? (I'm talking about the link in the bottom-left corner)

**Comment by iliakan** [comment]
Maybe Ctrl+Click it (or kind-of) ? :)

**Comment by iliakan** [comment]
New windows often confuse people.

**Comment by Kurczok** [comment]
Yeah, I use the middle mouse button, but I thought it would be more convenient. I understand your decision though ;)
