### ISSUE TITLE
Keyboard shortcut for back button 

### ISSUE THREAD

**Issue by naasking** [iliakan/javascript-tutorial-en#179]
For Chrome and FF on Windows:

 1. Click a title to go to a section.
 2. Hit alt-left arrow to back to the previous page.
 3. You end up at the previous chapter instead.

Hitting the back button works, but the keyboard shortcut for the back button does not.

**Comment by iliakan** [comment]
Actually I made that happen :/

Which shortcut you'd suggest for back-forward through the chapters?

**Comment by naasking** [comment]
Just left/right arrow keys are typically used in slides for back/forward, respectively.

**Comment by iliakan** [comment]
There are interactive examples, with inputs and such, arrow keys can be pressed there.

**Comment by javascript-plunk** [comment]
I mean, I can just remove that functionality, but maybe somehow adjust it.

**Comment by iliakan** [comment]
I mean, I can just remove that functionality, but maybe somehow adjust it.

**Comment by dagolinuxoid** [comment]
Users are pretty picky :). I am ok with the current state but have some suggestions: (alt + space+ arrow or shift + space + arrow or something like that seems reasonable).

**Comment by iliakan** [comment]
Proably fixed?
