### ISSUE TITLE
consistency in tutorials

### ISSUE THREAD

**Issue by devsnek** [iliakan/javascript-tutorial-en#180]
the first link i clicked on this tutorial landed me here:
![](https://gc.gy/èȚ.png)

double quotes, single quotes, bracket spacing, no bracket spacing.

If you're trying to teach people to learn a language you need to remain consistent. Possibly eslint your example code to make sure you keep a standard around or people will come out of the tutorial doing the same thing.

**Comment by iliakan** [comment]
Please see the "code style" article that explains the style.
