### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by Gutem** [iliakan/javascript-tutorial-en#206]
Opening this issue to inform I'll start translating it to pt-BR.
If someone want to help, PR my repo.

**Comment by iliakan** [comment]
Hi, cool!
You did not provide a link to the repo though.

**Comment by Gutem** [comment]
My fault:
https://github.com/Gutem/javascript-tutorial-br

**Comment by iliakan** [comment]
The translation is dead?

**Comment by iliakan** [comment]
Closing, guess nothing was actually done here.
