### ISSUE TITLE
Typo in 5-regular-expressions/15-regexp-infinite-backtracking-problem

### ISSUE THREAD

**Issue by Hobinx** [iliakan/javascript-tutorial-en#214]
In section Backtracking
"Then it tries to apply the start around the parentheses `(\d+)*`", "start" should be "star".

**Comment by iliakan** [comment]
Would you edit that on Github please? (Link at the left-bottom at the article)

**Comment by Hobinx** [comment]
I have created the pull request.

**Comment by iliakan** [comment]
I can't see it :(

**Comment by Hobinx** [comment]
Now you may see it. I created two pull requests just now.

**Comment by cpxPratik** [comment]
It's better to reference merged PR and close it.

**Comment by iliakan** [comment]
No, sorry I can't see the PR. Maybe you used another repo for it.

**Comment by Hobinx** [comment]
Sorry for that, now I think you can see them.
