### ISSUE TITLE
Minor: includes does not use '==='

### ISSUE THREAD

**Issue by usernamehw** [iliakan/javascript-tutorial-en#247]
This section https://javascript.info/array-methods#indexof-lastindexof-and-includes describes 3 mehtods:

`indexOf`/`lastIndexOf`/`includes`

and tells us that they are using `Strict Equality Comparison` (===) for searching.

But `includes` uses `SameValueZero`. The only difference from (===) – it can find NaN:

```javascript
const arr = [NaN];
console.log(arr.indexOf(NaN));// -1
console.log(arr.includes(NaN));// true
```

Maybe you can hide it under a spoiler "Advanced info" or something.

**Comment by lilifan** [comment]
Learned it，Thx for so careful!

**Comment by iliakan** [comment]
Added the info.
