### ISSUE TITLE
mentioning strict mode

### ISSUE THREAD

**Issue by amid11** [iliakan/javascript-tutorial-en#264]
[Function in if](https://javascript.info/closure#function-in-if)
```javascript
let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
```

> The result is an error.

> The function sayHi is declared inside the if, so it only lives inside it. There is no sayHi outside.

When I execute the code I don't get any error unless in strict mode, I think it can be a good idea to remind others that in order to see the error we need to add `'use strict';' at the top of our code

**Comment by iliakan** [comment]
Where to remind that? All code in the tutorial is use strict by default.

**Comment by amid11** [comment]
I meant for those who are running the code locally,  in their own js files, It took me awhile to remeber that I haven't used strict mode myself, so I thaught  a reminder wouldn't hurt anyone even though that was obviously my mistake.

**Comment by iliakan** [comment]
I understand, but where to put the reminder?

**Comment by amid11** [comment]
Maybe here https://github.com/amid11/javascript-tutorial-en/commit/e198ff7f764c5c2e9bd557ffcd8ae6f1a00e7933

**Comment by iliakan** [comment]
No, cause you see, there are many places in the tutorial like that. And also I believe strict mode is the past, not the present/future, don't like the idea of putting it into text at every such place.
