### ISSUE TITLE
Image error on "class patterns"

### ISSUE THREAD

**Issue by leorodr** [iliakan/javascript-tutorial-en#288]
Hello. I noticed that in the 'class patterns' chapter, there is a small error (if I am following correctly) in an image (link below). On the Rabbit.prototype box it should contain the 'jump' function, which is in the code immediately above the image.

https://github.com/iliakan/javascript-tutorial-en/raw/master/1-js/07-object-oriented-programming/08-class-patterns/rabbit-animal-independent-1.png

Nice work. Cheers.

**Comment by iliakan** [comment]
Yeah, right, fixed, thanks!
