### ISSUE TITLE
New function syntax is actually an example

### ISSUE THREAD

**Issue by usernamehw** [iliakan/javascript-tutorial-en#289]
https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/06-advanced-functions/07-new-function/article.md

As far as I understand `syntax` section in this tutorial usually a scheme similar to MDN. (not executable, general Idea). But this chapter uses real-life example as syntax:

```javascript
let func = new Function('a', 'b', 'return a + b');
``` 
Shouldn't it be:
```javascript
new Function ([arg1[, arg2[, ...argN]],] functionBody)
```

**Comment by iliakan** [comment]
Yep, fixed.
