### ISSUE TITLE
lint code

### ISSUE THREAD

**Issue by tomByrer** [iliakan/javascript-tutorial-en#317]
Current code examples are inconsistent style-wise (at least in longer & more edited docs).  You could [manually fix](https://github.com/iliakan/javascript-tutorial-en/pull/311), but might be better for a script to do it?

Maybe https://github.com/Qard/remark-lint-code
If you like stricter StandardJS: https://github.com/zeke/standard-markdown

**Comment by iliakan** [comment]
I had a script for that, guess it's still working, but not autorunning. Most of the code should be in linted state.
