### ISSUE TITLE
Translate into Japanese

### ISSUE THREAD

**Issue by KenjiI** [iliakan/javascript-tutorial-en#319]
I started to translate this into Japanese.
https://github.com/KenjiI/javascript-tutorial-ja

This issue is for informing about that. 
If some rules when I translate this, please let me know!

**Comment by iliakan** [comment]
Let us know how it does.

**Comment by KenjiI** [comment]
Hi, I'm a native Japanese speaker, and I'm translating this content into Japanese.
Now, I've translated "An introduction" and most of "JavaScript Fundamentals" in the PART1.

**Comment by iliakan** [comment]
Hi,

How experienced are you in JS? Do we need to make a technical review of the translation?

**Comment by KenjiI** [comment]
I've been using JS for many years, so at least I can understand the contents which I already translated 👍 
If there are some things I cannot understand when I translate, can I let you know ?

**Comment by iliakan** [comment]
Yes, of course.

**Comment by KenjiI** [comment]
Thanks a lot !

**Comment by iliakan** [comment]
I updated the local server to run the translation locally https://github.com/iliakan/javascript-tutorial-server, and also created a list of translations [here](https://github.com/iliakan/javascript-tutorial-en). 

Are you still translating/going to translate? If you do – please let me know.

**Comment by KenjiI** [comment]
Yes, I am continuing to translate [here](https://github.com/KenjiI/javascript-tutorial-ja).
Currently, most of PAR1 is finished.

**Comment by KenjiI** [comment]
@iliakan I have one question. When can we publish contents translated with other language like Japanese. Currently, for Japanese the translation of PART1 is finished except for some tasks and solutions. Are there any standard?
I'll continue to translate but I want to know that about PART1 the translation of remaining tasks are high priority or not. if it doesn't matter, I'd like to translate next PART. 
Any decision is ok for me :) Both works have a worth to tackle.
Thanks.

**Comment by iliakan** [comment]
Part 1 translated => publish

**Comment by KenjiI** [comment]
Ok, I'll do that

**Comment by KenjiI** [comment]
Hi, I'v finished to translate Part1 into ja. Also I confirmed it with https://github.com/iliakan/javascript-tutorial-server. 
Could you publish this ? or do I need to some work?

By the way, when I use https://github.com/iliakan/javascript-tutorial-server locally, all images on each article are be a "not found". Is it depends on my env or limitation of locally run?

**Comment by iliakan** [comment]
Hi,

Great, we'll be integrating `ja` to our main design then. 

That's strange,  https://github.com/iliakan/javascript-tutorial-server should work all right, what OS/Node version you use? What's the name of the catalog, is it `/js`?

Are there any errors in console? A screenshot?

**Comment by KenjiI** [comment]
Thanks a lot.

* My env is like this:
  OS: macOS High Siera 10.13.5
  Node: 9.11.2
* I'm using latest commit on https://github.com/iliakan/javascript-tutorial-server.

But when I do "./edit ja", the error below is occurred.
...
[21:28:47] 'tutorial:importWatch' errored after 958 ms
[21:28:47] TypeError: mime.lookup is not a function
    at /Users/<my dev path>/js/javascript-tutorial-server/handlers/tutorial/lib/tutorialImporter.js:579:21
...

So, to do launch correctly, I modify the code like below.
  handlers/tutorial/lib/tutorialImporter.js
```
  - let type = mime.lookup(file).split('/');
  + let type = mime.getType(file).split('/')
```

* Like above, I created the directory "js", and using it as a root folder.
* There are no error in console (just "not found" message is shown on the page. E.g "Image "/article/object/object.png" not found")

If there is any information I can provide you, please let me know.

**Comment by iliakan** [comment]
Please `git pull` the updated server and re-run.

**Comment by KenjiI** [comment]
Great, the latest commit works fine to my env! I could see all images.

But I found an another error. When I try to show the page "/js" or "/getting-started" (it means not an article page), 500 error will occur. That log is below.

```
{"name":"application","hostname":"HOST","pid":90774,"requestId":"09da916d-6c9b-4104-86cb-f549cdeac396","level":50,"message":"Pug file folder from code not resolved","stack":"Error: Pug file folder from code not resolved\n    at pugResolve (/Users/PATH/js/javascript-tutorial-server/modules/pugResolve.js:57:11)\n    at Object.ctx.render (/Users/PATH/js/javascript-tutorial-server/handlers/render.js:179:29)\n    at exports.get (/Users/PATH/js/javascript-tutorial-server/handlers/tutorial/controller/article.js:99:18)\n    at <anonymous>","referer":"http://localhost:3000/intro","cookie":"pixelRatio=1.7999999523162842","requestVerbose":{"method":"GET","url":"/js","headers":{"host":"localhost:3000","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://localhost:3000/intro","accept-encoding":"gzip, deflate, br","accept-language":"ja,en-US;q=0.9,en;q=0.8","cookie":"pixelRatio=1.7999999523162842"},"body":{},"ip":"127.0.0.1"},"msg":"","time":"2018-07-23T13:30:51.609Z","v":0}
```

**Comment by iliakan** [comment]
Could you please git pull the server once again?

**Comment by KenjiI** [comment]
I did that without any problem, thanks!

**Comment by iliakan** [comment]
Great, sorry for the unpolished stuff. Staying in touch in case you have other questions.

**Comment by KenjiI** [comment]
I started to translate for PART2 and I found an additional question in https://github.com/iliakan/javascript-tutorial-server.
Please let me know if I should create new issue on that repo.

For example, the page of localhost:3000/dom-nodes requires some JS to execute scripts. But it doesn't work, because can't get corresponding JS files.
The reason is that the path we should get is not "localhost:3000/libs/xxx", but "javascript.local/ilbs/xxx".
The easiest way to work is to change that defined on modules/config/index.js for now.

**Comment by iliakan** [comment]
Could you `git pull` please?

**Comment by KenjiI** [comment]
Great, works fine 👍

**Comment by KenjiI** [comment]
Thanks for your quick advice. Unfortunately, it still could not well. I tried some versions of webpack, but all of them occured an error.

Currently, I switched to some previous commit on https://github.com/iliakan/javascript-tutorial-server and doing translation on there (local server work fine).

```
❯ ./edit ja        
[11:18:00] Using gulpfile ~/Documents/program/js/javascript-tutorial-server/gulpfile.js
[11:18:00] Starting 'client:webpack'...
[11:18:00] Starting 'tutorial:importWatch'...
[11:18:00] 'tutorial:importWatch' errored after 366 ms
[11:18:00] Error: Pug file bemto.pug/lib/index from <path>/js/javascript-tutorial-server/modules/markit/templates/codeTabs.pug not resolved
    at <path>/js/javascript-tutorial-server/modules/markit/templates/codeTabs.pug line 1
    at Object.pugResolve [as resolve] (<path>/js/javascript-tutorial-server/modules/pugResolve.js:34:13)
    at Object.resolve (<path>/js/javascript-tutorial-server/node_modules/pug/lib/index.js:132:16)
    at <path>/js/javascript-tutorial-server/node_modules/pug-load/index.js:22:26
    at walkAST (<path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:23:18)
    at <path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:104:20
    at Array.reduce (<anonymous>)
    at walkAndMergeNodes (<path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:103:18)
    at walkAST (<path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:37:19)
    at load (<path>/js/javascript-tutorial-server/node_modules/pug-load/index.js:13:10)
    at Function.loadString [as string] (<path>/js/javascript-tutorial-server/node_modules/pug-load/index.js:46:10)
    at compileBody (<path>/js/javascript-tutorial-server/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (<path>/js/javascript-tutorial-server/node_modules/pug/lib/index.js:242:16)
    at Object.require.extensions..pug (<path>/js/javascript-tutorial-server/modules/lib/serverPug/index.js:13:22)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Gulp error details [ 'Pug file bemto.pug/lib/index from <path>/js/javascript-tutorial-server/modules/markit/templates/codeTabs.pug not resolved\n    at <path>/js/javascript-tutorial-server/modules/markit/templates/codeTabs.pug line 1',
  'Error: Pug file bemto.pug/lib/index from <path>/js/javascript-tutorial-server/modules/markit/templates/codeTabs.pug not resolved\n    at <path>/js/javascript-tutorial-server/modules/markit/templates/codeTabs.pug line 1\n    at Object.pugResolve [as resolve] (<path>/js/javascript-tutorial-server/modules/pugResolve.js:34:13)\n    at Object.resolve (<path>/js/javascript-tutorial-server/node_modules/pug/lib/index.js:132:16)\n    at <path>/js/javascript-tutorial-server/node_modules/pug-load/index.js:22:26\n    at walkAST (<path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:23:18)\n    at <path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:104:20\n    at Array.reduce (<anonymous>)\n    at walkAndMergeNodes (<path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:103:18)\n    at walkAST (<path>/js/javascript-tutorial-server/node_modules/pug-walk/index.js:37:19)\n    at load (<path>/js/javascript-tutorial-server/node_modules/pug-load/index.js:13:10)\n    at Function.loadString [as string] (<path>/js/javascript-tutorial-server/node_modules/pug-load/index.js:46:10)\n    at compileBody (<path>/js/javascript-tutorial-server/node_modules/pug/lib/index.js:86:18)\n    at Object.exports.compile (<path>/js/javascript-tutorial-server/node_modules/pug/lib/index.js:242:16)\n    at Object.require.extensions..pug (<path>/js/javascript-tutorial-server/modules/lib/serverPug/index.js:13:22)\n    at Module.load (internal/modules/cjs/loader.js:566:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:498:3)' ]
(node:84486) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[11:18:01] Entry module not found: TypeError: this.resourceRegExp.test is not a function
[11:18:01] 'client:webpack' errored after 712 ms
[11:18:01] Error: Entry module not found: TypeError: this.resourceRegExp.test is not a function
    at formatError (<path>/js/javascript-tutorial-server/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (<path>/js/javascript-tutorial-server/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:180:13)
    at Gulp.Orchestrator._emitTaskDone (<path>/js/javascript-tutorial-server/node_modules/orchestrator/index.js:264:8)
    at <path>/js/javascript-tutorial-server/node_modules/orchestrator/index.js:275:23
    at finish (<path>/js/javascript-tutorial-server/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (<path>/js/javascript-tutorial-server/node_modules/orchestrator/lib/runTask.js:29:3)
    at <path>/js/javascript-tutorial-server/tasks/webpack.js:30:28
    at finalCallback (<path>/js/javascript-tutorial-server/node_modules/webpack/lib/Compiler.js:154:39)
    at hooks.done.callAsync.err (<path>/js/javascript-tutorial-server/node_modules/webpack/lib/Compiler.js:170:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<path>/js/javascript-tutorial-server/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (<path>/js/javascript-tutorial-server/node_modules/tapable/lib/Hook.js:35:21)
    at onCompiled (<path>/js/javascript-tutorial-server/node_modules/webpack/lib/Compiler.js:168:21)
    at hooks.afterCompile.callAsync.err (<path>/js/javascript-tutorial-server/node_modules/webpack/lib/Compiler.js:488:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<path>/js/javascript-tutorial-server/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (<path>/js/javascript-tutorial-server/node_modules/tapable/lib/Hook.js:35:21)
Gulp error details []
```

By the way, for instance http://localhost:3000/mousemove-mouseover-mouseout-mouseenter-mouseleave, I found some of pages are not shown (500 error) in current my env. If I find the condition to occur this, I'll let you know or try to solve :)

```
{"name":"application","hostname":"<pc-name>.local","pid":85705,"requestId":"8f2ec413-19cb-42d8-9426-4a3fd2db7356","level":50,"message":"The \"path\" argument must be of type string","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string\n    at assertPath (path.js:39:11)\n    at Object.extname (path.js:1376:5)\n    at Object.md.renderer.rules.blocktag_codetabs (<path>/js/javascript-tutorial-server/modules/markit/plugins/blockTags/codetabs.js:32:22)\n    at Renderer.render (<path>/js/javascript-tutorial-server/node_modules/markdown-it/lib/renderer.js:326:38)\n    at TutorialParser.render (<path>/js/javascript-tutorial-server/modules/markit/serverParser.js:92:29)\n    at ArticleRenderer.render (<path>/js/javascript-tutorial-server/handlers/tutorial/renderer/articleRenderer.js:147:26)\n    at <anonymous>","referer":"","cookie":"pixelRatio=1.7999999523162842","requestVerbose":{"method":"GET","url":"/mousemove-mouseover-mouseout-mouseenter-mouseleave","headers":{"host":"localhost:3000","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"ja,en-US;q=0.9,en;q=0.8","cookie":"pixelRatio=1.7999999523162842"},"body":{},"ip":"127.0.0.1"},"msg":"","time":"2018-09-04T02:31:49.857Z","v":0}
```

**Comment by iliakan** [comment]
Did you pull the latest javascript-tutorial-server before reporting the error?

**Comment by iliakan** [comment]
I mean the one webpack-related yesterday. Did you pull before it?

**Comment by KenjiI** [comment]
I'm sorry, I had done without pulling the latest commit.
I pull the latest commit and tried again, an another error occur.
I tried with webpack's version 4.0.1, 4.10.2 and 4.17.2. Can I do anything to solve this?

```
❯ ./edit ja
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'jsengine/gulp/requireModuleTasks'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (<path>/js/javascript-tutorial-server/gulpfile.js:10:47)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by iliakan** [comment]
You reported the issue that was fixed long ago. 
So I was quite confused. Please don't do that.

Now I updated the tutorial to the refactored version, but I also need to update instructions how to run it. Will do that soon.

**Comment by iliakan** [comment]
Meanwhile you can `git checkout 51788d5324b1213a6532d00521b53ea7faa6bdf5`.
The latest before update.

**Comment by iliakan** [comment]
I updated the Readme. 

Now you can `git pull` latest, please reinstall server as described in Readme (now 2 repos instead of 1).

Changes are mostly internal, should not affect how you use it.

**Comment by iliakan** [comment]
Oh, which pages?

**Comment by KenjiI** [comment]
For example, 
http://localhost:3000/mousemove-mouseover-mouseout-mouseenter-mouseleave,
http://localhost:3000/mouse-drag-and-drop,
http://localhost:3000/keyboard-events

**Comment by iliakan** [comment]
Thanks a lot, please git pull, should work now.

P.S. git pull not only the root repo, but also `modules/jsengine`, please.

**Comment by KenjiI** [comment]
Hi, do you have any concrete plan to publish other languages like ja ? I've finished to translate PART1 and PART2 recently. Thanks for great contents :)

**Comment by iliakan** [comment]
Wow, that's really cool!

Sure, let's put it online for people ;)

Please fork the server code. It's in two repos:
- https://github.com/iliakan/javascript-tutorial-server
- https://github.com/iliakan/jsengine

It contains messages for site navigation etc.

Find all files named `en.yml`, copy them to `ja.yml` and translate into Japanese. 
Then please PR, so that the server can speak Japanese.

**Comment by iliakan** [comment]
And then we'll be able to publish it.

**Comment by KenjiI** [comment]
OK, I'll do that soon, thanks!

**Comment by KenjiI** [comment]
I have a question. Does the latest source works well?
When I get latest "javascript-tutorial-server" and "jsengine" and do "./edit ja", any page is not shown(all 404(not found)). 

Node: 10.9.0
Here is a part of logs when I did "./edit ja". Sorry if I've overlooked something.
```
❯ ./edit ja
[21:33:28] Using gulpfile <path>/javascript-tutorial-server/gulpfile.js
[21:33:28] Starting 'webpack'...
[21:33:29] Starting 'jsengine:koa:tutorial:importWatch'...
[21:33:30] Starting 'sync-resources'...
[21:33:30] Finished 'sync-resources' after 2.24 ms
[21:33:30] Starting 'livereload'...
[21:33:30] Starting 'server'...
(node:36826) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[21:33:30] 'jsengine:koa:tutorial:importWatch' errored after 528 ms
[21:33:30] Error: ENOENT: no such file or directory, open '<path>/javascript-tutorial-server/cache/tutorialViewStorage.json'
Gulp error details [ 'ENOENT: no such file or directory, open \'<path>/javascript-tutorial-server/cache/tutorialViewStorage.json\'',
  'Error: ENOENT: no such file or directory, open \'<path>/javascript-tutorial-server/cache/tutorialViewStorage.json\'' ]
12:33:30.433Z  INFO application: Server is listening localhost:3000
[21:33:30] Finished 'server' after 114 ms

```

**Comment by iliakan** [comment]
Please:
```
cd javascript-tutorial-server/modules/jsengine
git pull
```

Then try again.

**Comment by KenjiI** [comment]
Thanks for accepting my PR on both "javascript-tutorial-server" and "jsengine".
If there is more I need to do, please let me know.

**Comment by iliakan** [comment]
Please translate this. Right here is ok:
```
view_github: "view on Github"
search_placeholder: "Search in the tutorial"
search_button: "Search"
share_text: "Share"
```

**Comment by KenjiI** [comment]
OK, but which file should I add these translation? I searched but could not find the file "en.yml" which includes these strings. If any "ja.yml" files is ok to add these, will do it.

**Comment by iliakan** [comment]
Please change it here:
https://github.com/iliakan/javascript-tutorial-server/blob/master/modules/frontpage/locales/ja.yml

Also, the last line here:
https://github.com/iliakan/jsengine/blob/master/koa/tutorial/locales/ja.yml

**Comment by KenjiI** [comment]
Thank you. I'm done.

**Comment by KenjiI** [comment]
Thanks for your point. It is addressed in the PR (https://github.com/iliakan/javascript-tutorial-server/pull/17).

**Comment by iliakan** [comment]
I have it running on the staging server. Do you have an im (Telegram? Skype?) where I can send you credentials and ensure that you can see it in action?

**Comment by KenjiI** [comment]
Yes, I have a Skype account. That name is "live:espoir.ka".

**Comment by KenjiI** [comment]
Hi, here is a question.
Before merging PRs from others in other languages repo like  ja, checking CLA(Contributor License Agreement) is neccesarry as javascript.info?

**Comment by iliakan** [comment]
Actually, it's necessary for non-trivial additions, because signing CLA means that the author allows anyone to publish their changes and build on top of them. That's what he means by making a PR, but CLA makes it formally solid.

Should I add CLA to ja repostory?

**Comment by KenjiI** [comment]
> Should I add CLA to ja repostory?

If possible, please add ja repository.
Also do I need to let contributors accept it by using like the CLA assistant?

**Comment by iliakan** [comment]
Looks like I'm unable to do that, only you can :(

To do so, login at https://cla-assistant.io/, and then "configure CLA".
Here https://jmp.sh/awA7npC use this gist as CLA: https://gist.github.com/iliakan/9962ceab2894a12c3c508efed9e7f65f


https://gist.github.com/9962ceab2894a12c3c508efed9e7f65f

**Comment by KenjiI** [comment]
I could do this setting. Thank you!

**Comment by KenjiI** [comment]
Some svg files are not shown.
E.g 
svgs in https://ja.javascript.info/bezier-curve
A svg path is "http://ja.js.cx/article/bezier-curve/demo.svg?nocpath=1&p=0,0,0.5,0,0.5,1,1,1", but it's not found.

"http://en.js.cx/article/bezier-curve/demo.svg?nocpath=1&p=0,0,0.5,0,0.5,1,1,1" is exist(not ja.js.cx but en.js.cx).
Also  Chinese  site is same.

Do we have anything to do to show them correctly?
Thanks.

**Comment by iliakan** [comment]
Thank! Fixed?

**Comment by KenjiI** [comment]
Yes, work well!! Thanks you very much!
