### ISSUE TITLE
Broken syntax highlight for a task

### ISSUE THREAD

**Issue by usernamehw** [iliakan/javascript-tutorial-en#321]
http://javascript.info/basic-dom-node-properties#tag-in-comment

https://github.com/iliakan/javascript-tutorial-en/blob/master/2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md

https://github.com/iliakan/javascript-tutorial-en/blob/master/2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md

**Comment by iliakan** [comment]
Upgraded prismjs module, now looks good. Hope it doesn't fail elsewhere =)
