### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by artydev** [iliakan/javascript-tutorial-en#329]
Hello

I have forked the project
Do you have any suggestions ?

Regards

https://github.com/artydev/javascript-tutorial-fr

**Comment by iliakan** [comment]
Hi,

If you'd like to translate it into your language then fork the English tutorial and go ahead. I can publish the translation with your credits on a domain like fr.javascript.info when at least one part of the tutorial is ready.

**Comment by iliakan** [comment]
@artydev any progress?

**Comment by iliakan** [comment]
The translation appears to be dead, @SugoiNelson, feel free to apply as translation lead.

Not sure if @artydev ever did anything.

**Comment by iliakan** [comment]
There's no french translation.
