### ISSUE TITLE
Invite proofreaders (contributors) to this project

### ISSUE THREAD

**Issue by davegregg** [iliakan/javascript-tutorial-en#331]
The recent significant increase in this project's popularity and the backlog seem to indicate that this project could use more proofreaders. 

<sub>I'm willing to volunteer. I'm an instructor with a code school and I already have my students using this. So I'd like to help out in a few areas where I can.</sub>

**Comment by iliakan** [comment]
Sure, please submit changes via PRs, I'm steadily reviewing and accepting them, just probably not every day.
