### ISSUE TITLE
Old javascript.info content

### ISSUE THREAD

**Issue by sourav-kumar** [iliakan/javascript-tutorial-en#336]
Is it possible to share old javascript info content as I always gone thru that, please.

**Comment by iliakan** [comment]
Oh, I don't dare to publish it, because it's just outdated. Too many things has changed.

**Comment by sourav-kumar** [comment]
it was nt about publishing the content, I need those contents if you can share that with me, for some reference.

**Comment by sourav-kumar** [comment]
@iliakan just let me know if you are sharing it, as I really need to go through the patterns part.

**Comment by iliakan** [comment]
I do apologize, that's kind of difficult now. The old VM that was hosting it is down and archived.
