### ISSUE TITLE
Syntax error in an example 

### ISSUE THREAD

**Issue by MehyarSawas** [iliakan/javascript-tutorial-en#346]
Dear Javascript.info team,
Through reading your great tutorial, I have recognized a syntax error on the following page : 
https://javascript.info/javascript-specials#operators
Ternary section :  
result B  has space in between in the first row and the second row you've mentioned the same parameter but without space in between.
Best regards,
Mehyar Sawas

**Comment by thisisabdus** [comment]
I think that isn't an error. Because it is just an example and there is no actual code.

`cond ? resultA : result B` 

They put it to make us understand the process.

**Comment by MaxSchumacher** [comment]
Hi @MehyarSawas this is in fact an error. 

Feel free to correct it by cloning this page: https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/02-first-steps/16-javascript-specials/article.md then making your edits, commiting them and opening a PR for the maintainers.

**Comment by MehyarSawas** [comment]
Hi, @MaxSchumacher Thank you for your reply. 
I will gladly do it.
