### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by lmauromb** [iliakan/javascript-tutorial-en#348]
I'll start the Spanish translation.

Join me, if you know Spanish 😄 🇪🇸 

[https://github.com/lmauromb/javascript-tutorial-es](https://github.com/lmauromb/javascript-tutorial-es)

**Comment by MaxSchumacher** [comment]
the link to the spanish translation project is now in the readme, this issue can be closed

**Comment by SidVal** [comment]
Estás ahí @lmauromb  ?? 
Porque entré a ese repo y veo todo en inglés, vas a crear un nuevo branch para el español o cómo piensas organizar la traducción?

**Comment by SidVal** [comment]
Por eso te preguntaba del branch, pq vi que hiciste fork del repo en ingles, si cambiamos en el mismo "master", y después queres actualizar algo, no vamos a poder, porque volverías a pisar al inglés.

Vas a crear un branch aparte para "español" ?

**Comment by lmauromb** [comment]
El master de ese fork debe ser el trabajo en español, igual cree una branch `english` para que esa branch pueda ser usada como referencia al repo original.

Similar al fork de traducción en alemán, https://github.com/MartinEls/javascript-tutorial-de

**Comment by iliakan** [comment]
What's the news? Any progress?

**Comment by lmauromb** [comment]
Hi @iliakan,

We made a few decisions regarding how the translation will keep up with the upstream repo.

There is not many progress, besides a WIP glossary for translation terms (it would be uploaded to the fork README).

**Comment by iliakan** [comment]
I updated the local server to run the translation locally https://github.com/iliakan/javascript-tutorial-server, and also created a list of translations [here](https://github.com/iliakan/javascript-tutorial-en). 

Are you still translating/going to translate? If you do – please let me know.
