### ISSUE TITLE
Open Translate to Indonesian (ID)

### ISSUE THREAD

**Issue by anaufalm** [iliakan/javascript-tutorial-en#376]
Hello, I am very interested to read this project. May I translate this project into Indonesian? I am also an Indonesian translator. If allowed I will be happy to start translating this project. :)

Thank you.

**Comment by iliakan** [comment]
Just clone the repo and go ahead.

**Comment by anaufalm** [comment]
Ok, thanks

**Comment by anaufalm** [comment]
Can you make new repo for Indonesian? Like `/iliakan/javascript-tutorial-id` and give me access to commit and merge pr?

It will be better to make this done, while you not online sometime. :)

**Comment by iliakan** [comment]
Done.

**Comment by iliakan** [comment]
You are the collaborator in that repo!

**Comment by thickkoezz** [comment]
Hey, @iliakan. Gimana kabar translation-nya ke Bahasa Indonesia? Sudah selesai belum?

**Comment by thickkoezz** [comment]
Hey, @anaufalm. Gimana kabar translationnya. Sudah selesai ditranslate belum?
