### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rikakomoe** [iliakan/javascript-tutorial-en#387]
![javascript-tutorial-en/1-js/06-advanced-functions/03-closure/lexical-environment-global-3.png](https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/06-advanced-functions/03-closure/lexical-environment-global-3.png?raw=true)
Hello! Why the phrase in the picture is `Bye` here, is that a mistake?

**Comment by iliakan** [comment]
Could you give a link to that exactly place? I'll review ;)

**Comment by rikakomoe** [comment]
https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/06-advanced-functions/03-closure/lexical-environment-global-3.png

**Comment by venkatraj** [comment]
@rikakomoe Yes. It is a mistake. It should be `Hello`    
@iliakan This one http://javascript.info/closure#function-declaration

**Comment by iliakan** [comment]
fixed.
