### ISSUE TITLE
AT&T is hilariously direct linking to a font hosted on javascript.info

### ISSUE THREAD

**Issue by davegregg** [iliakan/javascript-tutorial-en#417]
This is really for the `javascript.info` site, not for this open source project per-se. But I thought I'd go ahead and document this here before I email the site runner.

Steps to reproduce (experienced on Firefox DE):
1. Navigate to ATT.com and log in.
2. Open your developer console (you may need to persist the logs).
3. Go to View Profile (https://www.att.com/my/#/passthrough/PROFILEOVERVIEW) and watch the console.
4. Near the top, you will see that they are loading Mixed Active Content from the following URL: http://javascript.info/pack/modules/styles/blocks/font/icons.4d2a69f8b521198cacb79fadc22a8c66.woff

If this is happening on View Profile, then it is probably happening elsewhere on their site. (NOTE: I haven't spent the time to track down where exactly this is being requested in their code.)

Why is this funny?
1. Because someone at AT&T is using javascript.info and thereby accidentally causing a Mixed Active Content bug by direct linking to a static resource.
2. Because a website which can handle traffic on the levels of ATT.com is relying on little javascript.info's server to deliver a font file.

**Comment by iliakan** [comment]
It's not a problem at all, because we're using CloudFlare CDN, so ATT gets served from CloudFlare. If they want it like that, I'm fine with it.

**Comment by iliakan** [comment]
To put it clear, our little server is behind a big bad beast who can serve that all and even don't get a hiccup.
