### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by t-cool** [iliakan/javascript-tutorial-en#434]
Hi.
I'd like to translate javascript-tutorial into Japanese.
I'll let you know when I finish it.

**Comment by KenjiI** [comment]
It looks duplication for the issue #319. How about? Thanks!

**Comment by iliakan** [comment]
I updated the local server to run the translation locally https://github.com/iliakan/javascript-tutorial-server, and also created a list of translations [here](https://github.com/iliakan/javascript-tutorial-en). 

Are you still translating/going to translate? If you do – please let me know.

**Comment by KenjiI** [comment]
@t-cool Hi, as I said previously, I'm translating into Japanese on [my repo](https://github.com/KenjiI/javascript-tutorial-ja) (work in progress). So please use here for the case of Japanese.

**Comment by iliakan** [comment]
Please add me as a contributor.

**Comment by iliakan** [comment]
Per @KenjiI words, the translation is quite alive, I added a link in the front readme.

I just run it locally, and it looks nice so far, but a little bit enigmatic, as I don't understand Japanese ;) Hope you can proofread it ;)

**Comment by KenjiI** [comment]
Of course.  I also ran my repo locally with https://github.com/iliakan/javascript-tutorial-server (this is great!), and I found that I need some more work. I'll tackle that :)
@t-cool It would be awesome if you could proofread, as I know JavaScript but I'm not an expert for translation :)
