### ISSUE TITLE
Uzbek Translation

### ISSUE THREAD

**Issue by aruzikulov** [iliakan/javascript-tutorial-en#439]
Opening this issue to inform I'll start translating it to Uzbek Language.
If someone want to help, PR my repo.
https://github.com/aruzikulov/javascript-tutorial-uz

**Comment by iliakan** [comment]
I updated the local server to run the translation locally https://github.com/iliakan/javascript-tutorial-server, and also created a list of translations [here](https://github.com/iliakan/javascript-tutorial-en). 

Are you still translating/going to translate? If you do – please let me know.

**Comment by aruzikulov** [comment]
still doing translation, it would be great if you add uz.javascript.info that I can encourage Uzbek community to help me to translate. Thanks

**Comment by iliakan** [comment]
OK. Please commit to git as you do, so that people can see that the translation is alive.

**Comment by iliakan** [comment]
The translation is dead? I don't see progress.

**Comment by aruzikulov** [comment]
was busy for a while, will start soon

**Comment by iliakan** [comment]
Removing it from the list. Will re-add if enough if translated.
