### ISSUE TITLE
Typo in the Numbers page

### ISSUE THREAD

**Issue by davidbludlow** [iliakan/javascript-tutorial-en#442]
Look at the page at https://javascript.info/number

This quote from that page doesn't make sense: "They 'read' a number from a string until they can. In case of an error, the gathered number is returned. "

Perhaps you meant to say "They 'read' a number from a string until there is no more number to read. When they reach a part of the string that is not a number, the gathered number is returned."

**Comment by iliakan** [comment]
Please change and make a PR? You can edit the article (see the left-bottom corner of the window).
