### ISSUE TITLE
Add good search experience to the documentation

### ISSUE THREAD

**Issue by s-pace** [iliakan/javascript-tutorial-en#443]
👋  first of all thank you for your wonderful website.

I couldn't help me providing a [good search experience for you good documentation](https://community.algolia.com/docsearch/), see below a preview:

![Preview](https://cl.ly/3D1S12262t2b/download/Screen%20Recording%202018-06-18%20at%2002.42%20PM.gif)

You can [try out a quick showcase here](https://javascriptinfo-docsearch.surge.sh/)

Please note that the [the google site search will be completely shut down by April 1, 2018.](https://enterprise.google.com/search/products/gss.html)

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'b332e6c2ef6c0c5cd4aea0fb9cd41ffb',
  indexName: 'javascript_info',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Optionally customize the look and feel by following [the DocSearch documentation](https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration [in our GitHub repo](https://github.com/algolia/docsearch-configs/blob/master/configs/javascript_info.json).

Please open a pull request if want to leverage your configuration! We do provide **search analytics on the use of your tool**.

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it. Happy to PR your project.

Have a nice day :)

**Comment by iliakan** [comment]
You mean using a 3rd party tool for that?

**Comment by s-pace** [comment]
Hi @iliakan, 

Sorry I didn't understand your question.

Could you give me much details please?

**Comment by iliakan** [comment]
I mean, do you suggest to make use of a 3rd-party service to achieve that?

**Comment by s-pace** [comment]
*Disclaimer: It might not be clear enough from my previous message but I am working on this project (DocSearch).*

I do think using our tool will be a good way to achieve that since it comes out of the box, the search is typo-tolerant and results are appearing really fast.

I am biased on this question so I let you [try it out](https://javascriptinfo-docsearch.surge.sh/) and give me your feedback on it.

**Comment by iliakan** [comment]
Oh, I did not find such phrase in the message. Now I understand.

If it is so, probably you can answer some questions about your system:

1) Your engine performs indexing and search? It integrates with our API, so that we submit documents?
2) How much that costs? 

Right now we use Elasticsearch, we can just add an autocompletion script to show results and, well, have the same =)

**Comment by iliakan** [comment]
@s-pace

**Comment by s-pace** [comment]
Hi @iliakan,

It is an alternative to ElasticSearch. The limitation your are describing are for the community plan. DocSearch is focus on open source documentation and since your content is really helpful for the developer community, we would love to increase these limitations.

**Comment by s-pace** [comment]
Let me know @iliakan if you have any question. Happy to provide you any help in order to make it happen

**Comment by iliakan** [comment]
@s-pace it appears that your search is bugged. Try searching "alert Enter".

It also returns "center" and "external", but that's wrong.

**Comment by s-pace** [comment]
👋 @iliakan 

This is not a bug. It is actually expected since there is some [**typo tolerance**](https://www.algolia.com/doc/guides/textual-relevance/typo-tolerance/). Given that we didn't pickup code elements at the crawling time, `alert enter` is not matching any specific record. As a fallback, our engine is looking for alternatives so we are matching `exter` (with a typo from enter) and `enters` too.

 Please note that we only highlight part of the records and not the whole word like center or external.

![image](https://user-images.githubusercontent.com/32097720/42495617-d2ff8020-8423-11e8-9c69-50516d2625c2.png)

This typo tolerance might be quite useful for your user since it brings a learn as you type experience with the dropdown.


If you can point me which pages you wanted to retrieve on, I can enhance your configuration in order to pick up the right content from your page. Let us know.

NB: In order to look for the expected result, I have used your current search but It has failed:
![image](https://user-images.githubusercontent.com/32097720/42495341-181e0060-8423-11e8-9aa2-5a0146fd73bb.png)
[Link to the requested page](https://javascript.info/search/?query=alert+enter&type=articles)

**Comment by iliakan** [comment]
yeah sorry we had a downtime on elastic =(

http://javascript.info/search/?query=alert+enter

**Comment by s-pace** [comment]
Makes sense @iliakan .

If you have any feedback, happy to collect them in order to enhance our tool.
