### ISSUE TITLE
Attention: function example for 2.15 section is really odd to me 

### ISSUE THREAD

**Issue by dagolinuxoid** [iliakan/javascript-tutorial-en#451]
function example for 2.15 is odd to me
```javascript
let age = prompt("What is your age?", 18);

// conditionally declare a function
if (age < 18) {

  function welcome() {
    alert("Hello!");
  }

} else {

  function welcome() {
    alert("Greetings!");
  }

}

// ...use it later
welcome(); // Error: welcome is not defined
```
I don't think that calling of the welcome function will produce an error since if/else blocks do not establish new scope for functions I believe.

**Comment by antzshrek** [comment]
The `welcome()` should work fine and error free.

**Comment by dagolinuxoid** [comment]
@antzshrek, yep exactly — it should work fine, but in the tutorial issuing `welcome();` produces Error. «That’s because a Function Declaration is only visible inside the code block in which it resides.»

**Comment by iliakan** [comment]
Welcome should NOT work. The tutorial explains why.

**Comment by dagolinuxoid** [comment]
es6. thx your answer. I overlooked 'use strict', my bad.
