### ISSUE TITLE
Translation to french

### ISSUE THREAD

**Issue by SugoiNelson** [iliakan/javascript-tutorial-en#452]
Since the last one is dead, I forked the project.

Here's the said fork : https://github.com/SugoiNelson/javascript-tutorial-fr

I'll only be able to work on it during the weekends so it might take some time before it's completely done, thanks for understanding.

**Comment by iliakan** [comment]
I'll add this one to the front Readme then.

**Comment by iliakan** [comment]
Removing it from the list. Will re-add if enough if translated.

**Comment by SugoiNelson** [comment]
Been some busy months lately, might work on it if anyone can help me but it's too much work for the too little free time I have, sorry.
