### ISSUE TITLE
Translation In Hindi

### ISSUE THREAD

**Issue by ravipasha** [iliakan/javascript-tutorial-en#457]
Hi Admin Team,
Your work is simply amazing, the details are matchless and awesome. I want to Translate the entire work in one of the most spoken language in word i.e Hindi, the Language of India. 
I believe this will help the website reaching to more people here. 
Please Let me know the way forward.

Ravi Kumar

**Comment by iliakan** [comment]
If you'd like to translate it into your language, please create/clone the repository, name it "javascript-tutorial-hi" (by the language) and create an issue for me to add you to the list.
