### ISSUE TITLE
Starting a danish translation

### ISSUE THREAD

**Issue by ockley** [iliakan/javascript-tutorial-en#461]
Hi, @iliakan - I am starting a Danish translation at https://github.com/ockley/javascript-tutorial-da. Do you have any suggestions on good strategies in the writing. There used to be a rich editor inside GitHub, but I can't find it anymore.

Do you use Gitbook or other tool?

Best Wishes
Karsten

**Comment by iliakan** [comment]
Did you check this one? https://github.com/iliakan/javascript-tutorial-server/

**Comment by ockley** [comment]
I didn't try that one - I thought it was for showing the final text only. Does it have editing capabilities as well? For now, my best choice is to settle with Gitbook (https://ockley.gitbook.io/javascript/) but I would rather edit directly on GiyHub.

**Comment by iliakan** [comment]
You can edit anywhere, markdown-like syntax.

The server shows how it looks immediately in case you want to see it. 

It's not gitbook, because the tutorial uses some custom stuff not supported by gitbook.

**Comment by iliakan** [comment]
Added the translation to the list.

**Comment by ockley** [comment]
OK, great. I stick with the server listed above and see how it spins - thanks.
