### ISSUE TITLE
Translation to Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by paulocezzar** [iliakan/javascript-tutorial-en#484]
Hi I am starting a pt-br translation. Would appreciate if you could add it to the list. Also, I would appreciate any help from fellow countrymen.
Thanks! PC

**Comment by iliakan** [comment]
Show me the repository please. How's the translation going?

**Comment by paulocezzar** [comment]
Here are what I have done so far.

https://github.com/paulocezzar/javascript-tutorial-pt-br-master/blob/master/1-js/01-getting-started/1-intro/article.md

**Comment by CleverMatias** [comment]
Hi Paulo cezar I can help you with the translation send me a message on 5541995246540 thanks

**Comment by paulocezzar** [comment]
Hi, you are welcome to help. Please do.

**Comment by iliakan** [comment]
Is the translation alive? @CleverMatias @paulocezzar

**Comment by paulocezzar** [comment]
Hey, can you sign this petition? https://chn.ge/2CkarJM

Thanks! - Paulo

**Comment by iliakan** [comment]
Probably stalled and inactive.
