### ISSUE TITLE
Hindi Translation (javascript-tutorial-hi)

### ISSUE THREAD

**Issue by NishiGaba** [iliakan/javascript-tutorial-en#488]
Here, I am creating an issue for translating javascript.info into the Hindi version. I would appreciate if you could add it to the list. Any help is welcome. :)

Thanks!

**Comment by iliakan** [comment]
Show me the repository please. How's the translation going?

**Comment by NishiGaba** [comment]
Hi, Here is the link of repository : [javascript-tutorial-hi](https://github.com/NishiGaba/javascript-tutorial-hi) and translation is in progress :)

**Comment by iliakan** [comment]
Probably stalled.
