### ISSUE TITLE
Wrong reason for the given problem

### ISSUE THREAD

**Issue by gustavorincon55** [iliakan/javascript-tutorial-en#492]
This is all in 

javascript-tutorial-en/5-regular-expressions/08-regexp-greedy-and-lazy/

Hello! I have read all your articles of regexp so far. And they all are excellent and have helped me a lot, thank you!

 Please correct me if i'm wrong but I think there is a mistake in this article. When you went to explain a second example in which the lazy mode won't work, you assumed that the code was wrong and the solution you gave was to replace the `<a href=".*?"</code> with <code> <a href="[^"]*"`.

However the reason why it didn't work is because the class in the string is not "doc". In that example the class in the string is "wrong". 

I hope all of this is more clear with this pictures:

![png-1](https://user-images.githubusercontent.com/40842358/44951311-64a48680-ae2f-11e8-827e-2c3140873758.png)

![png-2](https://user-images.githubusercontent.com/40842358/44951310-63735980-ae2f-11e8-9d7b-94b18f993554.png)

Now, in the second picture, you can see that the second example didn't work on the first string because the class was still "wrong". However you then traid with the second string, and of course it works, because on that string the class is "doc". 

I think you wanted to explain a different solution for that problem. I'd say you can use another regex so it gives you the result you want.

` let reg = "/<a href=".*?" class=".*?">/g"; `

So it will be 

`let str = ...<a href="link1" class="wrong"></a>... <a href="link2" class="doc"></a>...;`
`let reg = /<a href=".*?" class=".*?">/g;`

`// Works!`
`alert( str.match(reg) );`

Result: `<a href="link1" class="wrong">, <a href="link2" class="doc">`

Now, don't get me wrong, you are doing a wonderfull job explaining very difficult concepts. I give you props for that, and hope others get as much help as I do.

pd: English is not my main lenguage so i hope i  didn't make any mistakes.

**Comment by iliakan** [comment]
Sorry for the late answer. Did you figure things out?

**Comment by gustavorincon55** [comment]
Hello! Sorry but i still think this explanation is off.

Maybe if you read this part (<a href="https://javascript.info/regexp-greedy-and-lazy#greedy-search">page</a>):

![mistake-example1](https://user-images.githubusercontent.com/40842358/47272509-d0b08a80-d554-11e8-8cc5-bd79068dc87b.jpg)






-
-
-
-

![example 2](https://user-images.githubusercontent.com/40842358/47272570-8bd92380-d555-11e8-8fd1-6baacf5a3113.PNG)
