### ISSUE TITLE
PWA on iOS 11.4

### ISSUE THREAD

**Issue by Bearsie** [iliakan/javascript-tutorial-en#493]
Every time I launch javascript.info on iPad (iOS 11.4) through the home screen icon, and then I click some chapter, it's opened in new tab in Safari and whole PWA experience is gone. It's so irritating. Is it possible to make it better? On android it works great!

**Comment by iliakan** [comment]
What you mean "launch javascript.info"?

**Comment by iliakan** [comment]
We don't have PWA app.

**Comment by iliakan** [comment]
I can't be responsible for an app made by someone even without my permission.
