### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by giulp** [iliakan/javascript-tutorial-en#506]
I'm beginning to translate javascript.info to Italian language. 
Don't have much time but I'll notify of progress.
It goes without saying, any help from Italian speaking devs is appreciated
thank you :)

**Comment by giulp** [comment]
sorry, no feedback whatsoever after 11 days is too little for me :)

**Comment by iliakan** [comment]
What feedback you'd want to see?

You didn't supply any link to your translation repo.

**Comment by giulp** [comment]
Hi Ilya,

I followed your instructions to the letter:

'If you'd like to translate it into your language, please clone the
repository, change its name to javascript-tutorial-... (by the language)
and create an issue for me to add you to the list.'

was waiting for something on the lines of "I'll add it when it reaches X%"

In any case I don't have the time to follow this translation, sorry.
Have a nice day,
sincerely
Giulio


2018-09-24 16:48 GMT+02:00 Ilya Kantor <notifications@github.com>:
