### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Tchoupinax** [iliakan/javascript-tutorial-en#508]
Hey, 

French translation just started here. Updates and work on it as much as possible. :)
https://github.com/Tchoupinax/javascript-tutorial-fr

Congratulations for your work ! 

Regards,

**Comment by iliakan** [comment]
I'll add it to the official list when 3% or more is translated ;)

**Comment by Tchoupinax** [comment]
How do you check the percentage ? :)

**Comment by Tchoupinax** [comment]
First page translated and i will continuing little part by little part. :)
Just asking because i'm curious to see my progress.

**Comment by iliakan** [comment]
I have scripts for that, when you translated several articles, we can add your translation to the list in Readme.md, and the percentage will be there :)

**Comment by iliakan** [comment]
Please take a look at https://github.com/HachemiH/javascript-tutorial-fr
Maybe you join the efforts?

**Comment by Tchoupinax** [comment]
Contacted him.
