### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by HachemiH** [iliakan/javascript-tutorial-en#512]
Hi,

I started the french transation of your amazing work.
The count is stucked at 0% on my repo.

https://github.com/HachemiH/javascript-tutorial-fr

Best regards

**Comment by iliakan** [comment]
Please take a look at https://github.com/Tchoupinax/javascript-tutorial-fr
Maybe you join efforts?

**Comment by iliakan** [comment]
Guess, this rabbit's dead ;(.

**Comment by HachemiH** [comment]
Hi iliakan, i don't know for Tchoupinax, but i'm still working on it, it's by far the best js course i've seen, you can count on me for this translation.

**Comment by iliakan** [comment]
Oh, I just saw the latest commit was 27 days ago.

**Comment by HachemiH** [comment]
yes but don't worry i'm still on it, just lot of work this month, this weekend i continue.

**Comment by iliakan** [comment]
Added the translation to the readme.
