### ISSUE TITLE
Task at "Modifying the document" is at wrong section

### ISSUE THREAD

**Issue by Ghost-017** [iliakan/javascript-tutorial-en#524]
I believe the task [Colored clock with setInterval](http://javascript.info/modifying-document#colored-clock-with-setinterval) is supposed to be in the "Styles and classes" section.

**Comment by iliakan** [comment]
There's no work on styles/classes there. Only elements.

**Comment by Ghost-017** [comment]
Nevermind, I thought I was supposed to create a colored clock using only pure JS.

**Comment by iliakan** [comment]
Okay, maybe it's worth to add a few notes about that for people.

**Comment by iliakan** [comment]
So that they use the pre-filled document.
