### ISSUE TITLE
Suggestion: library for End 2 End Testing 

### ISSUE THREAD

**Issue by Chofoteddy** [iliakan/javascript-tutorial-en#552]
[Acceptance Tests](http://www.extremeprogramming.org/rules/functionaltests.html) can be a great complementary content for explains to the coders how can test functional requirements.

[CodeceptJS](https://codecept.io/) is a library that provides a friendly way to do that.

Grettings.

**Comment by iliakan** [comment]
Write an article, make PR? :)
