### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Chofoteddy** [iliakan/javascript-tutorial-en#553]
![imagen](https://user-images.githubusercontent.com/1615875/47020552-36e57980-d11f-11e8-8e5e-aab570fe81a4.png)

From page: http://javascript.info/testing-mocha

http://plnkr.co/edit/todpkmwwlo?p=preview
http://plnkr.co/edit/bi9enmmreao?p=preview

**Comment by iliakan** [comment]
Are links ok now?

**Comment by Chofoteddy** [comment]
Both shows an error:

![screenshot from 2018-10-16 20-14-12](https://user-images.githubusercontent.com/1615875/47056057-37fac300-d180-11e8-930e-3c5f293fb903.png)

**Comment by iliakan** [comment]
I mean, there should no be such links on the page. There are other, working links.

**Comment by iliakan** [comment]
Please check the tutorial page, it should be ok now. If not, let me know =)

**Comment by ranwise** [comment]
@iliakan планкер пишет что нету какого-то импорта и редиректит на стартовый шаблон

**Comment by iliakan** [comment]
Можно ссылку на статью, в которой это происходит?

С уважением,
Илья Кантор

**Comment by iliakan** [comment]
I'm sorry, it's actually my fault, the new deploy mechanism is not perfect, I'll fix it soon.
