### ISSUE TITLE
Missing solution 

### ISSUE THREAD

**Issue by jessuni** [iliakan/javascript-tutorial-en#554]
The external linked page of the solution in task https://javascript.info/task/create-list doesn't contain any solution.

**Comment by iliakan** [comment]
What's the link?

**Comment by iliakan** [comment]
Give a screenshot?

**Comment by jessuni** [comment]
http://plnkr.co/edit/ulbbr3h82e?p=preview
![image](https://user-images.githubusercontent.com/41285428/47069965-d17ab100-d222-11e8-93ae-4ed7b99a5269.png)

![image](https://user-images.githubusercontent.com/41285428/47069885-9ed0b880-d222-11e8-91bc-ad91cc0fba6a.png)

**Comment by iliakan** [comment]
That's a wrong link. It's a dev link actually, should have been replaced.

Could you refresh the page, clear the cache?

**Comment by jessuni** [comment]
It works now.
