### ISSUE TITLE
uncentered placement of  'Filter by title'  inside search input 

### ISSUE THREAD

**Issue by dagolinuxoid** [iliakan/javascript-tutorial-en#568]
In Firefox placeholder's text inside search bar has an ugly view. 
In order to center it `.text-input__control` must have `padding: 8px` instead of `4px`. Actually in Chrome with padding: 8px it also looks nicer - it's not that close to the left corner. Take a look at the screenshot (on top 4px on bottom 8px). PS. I didn't find the stylesheet file in the repository :) so I wasn't been able to correct it and make the pull request on my own.

[![placeholderfox.png](https://i.postimg.cc/jSVhWThS/placeholderfox.png)](https://postimg.cc/1fHFTLTk)

**Comment by iliakan** [comment]
In my firefox: https://jmp.sh/qse0CV6
Needs to be fixed, indeed.

**Comment by iliakan** [comment]
@bussebu please check http://javascript.info/array-methods?map
