### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by Yeonjj** [iliakan/javascript-tutorial-en#590]
Here, we just stated Korean translation.
https://github.com/Yeonjj/javascript-tutorial-ko

**Comment by iliakan** [comment]
Great! Let me know when several articles are done, I'll include it into the official translations list!

**Comment by Yeonjj** [comment]
Alright, Thanks!

**Comment by Violet-Bora-Lee** [comment]
Hello, @iliakan 
I want to translate your repository in Korean.
I've cloned and made the [repository](https://github.com/Violet-Bora-Lee/javascript-tutorial-ko) today and @Yeonjj is also translating your repo in Korean. 
Could you let me know the better strategy when the multiple translator have cloned your repository and are translating?

**Comment by Yeonjj** [comment]
I guess the better strategy is to integrate our repository one way or another. 

If you disagree with conventions or the way of running repository, Feel free to make an [issue](https://github.com/Yeonjj/javascript-tutorial-ko/issues?q=is%3Aissue+is%3Aclosed) so that we can discuss it. We can talk in Korean in the repository :)

If you want me to merge translated [articles](https://github.com/Yeonjj/javascript-tutorial-ko/issues?q=is%3Aissue+is%3Aclosed) into your repository, as an alternative, that also would be the way of keeping it simple. (In case you already started translating, check what articles are translated to avoid redundant work)

**Comment by iliakan** [comment]
@Yeonjj , how's the progress? I entered the very first article, and it's not translated.

You translated only 3 articles (listed in issues) ?

**Comment by Yeonjj** [comment]
Yes, That's all the articles I translated so far. I'm so glad that I have a company to accelerate the progress :)

**Comment by Violet-Bora-Lee** [comment]
FYI

I've made the [dashboard](https://docs.google.com/spreadsheets/d/1fYaEI8vz26N3R2VaxrlNnk9fMQ8zIy4RpvjRp4jZd0Q/edit#gid=0) to see the progress of the translation.

Moreover, I've made [translation sheet](https://docs.google.com/spreadsheets/d/1mxlxTwqdQwxkxrqMWqHgGT6lCKgj8HqCZ3UioQLAvL0/edit#gid=0) in order to improve the translation quality.

Some member from Women Who Code Seoul will join the translation soon.

**Comment by iliakan** [comment]
I couldn't access the dashboard, not permissions.

I only can see that the last commit to master was 29 days ago.

**Comment by Violet-Bora-Lee** [comment]
Here is my [repository](https://github.com/Violet-Bora-Lee/javascript-tutorial-ko/commits/master).

[dashboard](https://docs.google.com/spreadsheets/d/1fYaEI8vz26N3R2VaxrlNnk9fMQ8zIy4RpvjRp4jZd0Q/edit?usp=sharing)

[translation sheet](https://docs.google.com/spreadsheets/d/1mxlxTwqdQwxkxrqMWqHgGT6lCKgj8HqCZ3UioQLAvL0/edit?usp=sharing)

**Comment by Violet-Bora-Lee** [comment]
yes, we are working in a different repository. But we made some agreement to avoid duplicated translation. Koreans translators could read the guide in my readme.md file. I'm merging @Yeonjj's master branch into my repository.

**Comment by iliakan** [comment]
Great, added it to the readme.
