### ISSUE TITLE
Run button not working (Chapter 2.4)

### ISSUE THREAD

**Issue by MichalKarbownik** [iliakan/javascript-tutorial-en#603]
The bug exists in the chapter 2.4 - [Variables](https://javascript.info/variables/#variable-naming). In the "An assignment without `use strict`" box, the button of the second code does not work.

- [x] Tested on Firefox, Chrome and Edge

**Comment by jonahcwest** [comment]
The second box is not supposed to work. Further, it doesn't do anything that the user can see.

**Comment by MichalKarbownik** [comment]
@jonahcwest So maybe it's worth to remove the 'run' button to avoid confusion.

**Comment by iliakan** [comment]
Okay I'll remove it.
