### ISSUE TITLE
Incorrect button title tag

### ISSUE THREAD

**Issue by jayhybrid** [iliakan/javascript-tutorial-en#606]
On https://javascript.info/type-conversions, at the bottom of the page when clicking on the **solution** button and hovering over the close **X** button, the title tag is not in english but rather *закрыть*. I think this applies to all **X** buttons.

**Comment by dagolinuxoid** [comment]
@jayhybrid you're right it's a global thing - good catch.

**Comment by iliakan** [comment]
was fixed some time ago, thanks.
