### ISSUE TITLE
Clarification on an execution context of the next() method in Iterables

### ISSUE THREAD

**Issue by dagolinuxoid** [iliakan/javascript-tutorial-en#620]
In the [iterables chapter](https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/05-data-types/06-iterable/article.md) you've mentioned that "When for..of wants the next value, it calls next() on that object." It's an accurate assertion but consider to emphasize/clarify it. Maybe make a note afterwards. So basically `for of` doesn't call `next()` as a standalone function on its own but rather in a context of the object which *"owns"* the `next` method - it performs something like `next.bind(ObjectReturnedbySymbolIteratorMethod)()`. Also using of arrow functions to represent `next` method will produce unexpected  result because such functions retain `this` from lexical environment in which they're declared.

**Comment by iliakan** [comment]
The value of `this` should be obvious from the very first example with `range`.

**Comment by iliakan** [comment]
Added more clarifications.
