### ISSUE TITLE
Subscribe button error

### ISSUE THREAD

**Issue by ruben-vargas** [iliakan/javascript-tutorial-en#624]
There's a bug with the subscribe btn for all courses 
<code>https://javascript.info/courses/*</code>

It fires an alert message **"Choose newsletters in the list."** on click.

<img width="1440" alt="js-info-bugs" src="https://user-images.githubusercontent.com/43826685/48584289-4f4fdc00-e8f7-11e8-812e-50ed307676f7.png">

**Comment by iliakan** [comment]
Is it ok now?

**Comment by ruben-vargas** [comment]
Perfect!
