### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by lighthousand** [iliakan/javascript-tutorial-en#627]
Hello ! I started the romanian translation here https://github.com/lighthousand/javascript-tutorial-ro.git

**Comment by iliakan** [comment]
Great!
Please write here when several articles are translated, I'll add it to the Readme.

**Comment by lighthousand** [comment]
Hello, is not much but i managed to translate the first 3 small chapters of introduction (intro, code-editors and devtools).

**Comment by iliakan** [comment]
Added to the Readme https://github.com/iliakan/javascript-tutorial-en.

The percentage is yet small, so I put "started", I will add the numbers later.
