### ISSUE TITLE
Array : Trailing comma

### ISSUE THREAD

**Issue by stanpetit** [iliakan/javascript-tutorial-en#659]
Hi all  :)

Trailing comma : in [https://javascript.info/array](https://javascript.info/array)

see: 
[JSON.parse() does not allow trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#JSON.parse()_does_not_allow_trailing_commas)

// both will throw a SyntaxError
JSON.parse('[1, 2, 3, 4, ]');
JSON.parse('{"foo" : 1, }');

Best, Stan

**Comment by iliakan** [comment]
JSON format is not the same as JS.
