### ISSUE TITLE
Dari Translation

### ISSUE THREAD

**Issue by luckyjavid** [iliakan/javascript-tutorial-en#688]
Hi I wanted to contribute and start translating this tutorial into Dari.

**Comment by iliakan** [comment]
If you'd like to translate it into your language, please clone the repository, change its name to javascript-tutorial-... (by the language) and create an issue for me to add you to the list.

You can edit the text in any editor (markdown-like syntax). The server to run the tutorial locally and see how it looks is at https://github.com/iliakan/javascript-tutorial-server.
