### ISSUE TITLE
make the demo more clear

### ISSUE THREAD

**Issue by web1992** [iliakan/javascript-tutorial-en#695]
I see the following code here:

[12-arrow-functions/article.md](https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/06-advanced-functions/12-arrow-functions/article.md)

```js
function defer(f, ms) {
  return function() {
    setTimeout(() => f.apply(this, arguments), ms)
  };
}

function defer(f, ms) {
  return function(...args) {
    let ctx = this;
    setTimeout(function() {
      return f.apply(ctx, args);
    }, ms);
  };
}
```

if we change:
```diff
- setTimeout(() => f.apply(this, arguments), ms)
+ setTimeout(() => f.apply(null, arguments), ms)

- let ctx = this;
- return f.apply(ctx, args);
+ return f.apply(null, args);
```
after: 

```js
function defer(f, ms) {
  return function() {
    setTimeout(() => f.apply(null, arguments), ms)
  };
}

function defer(f, ms) {
  return function(...args) {
    setTimeout(function() {
      return f.apply(null, args);
    }, ms);
  };
}
```

I think this will make demo more clear. 
In demo the `...args` is the only value we use.
So I think `applay(this)` can be `applay(null)`. 
`this` never is a customer object,it always is `window` object.

**Comment by iliakan** [comment]
`this` is generally needed for the function to work with object methods.
