### ISSUE TITLE
Major Typo in Developer Console page

### ISSUE THREAD

**Issue by Lite3000** [iliakan/javascript-tutorial-en#711]
"But in the browser, _users doesn't_ see errors by default."
It should be, "But in the browser, users don't see errors by default."
How do you know I'm right? Well, I've been studying the English language for 17 years. It's almost as if I just finished reading the dictionary.

**Comment by iliakan** [comment]
That's a typo, right, please send a PR.

**Comment by imidom** [comment]
Hi! My fault for missing that on my last PR. Pushed a new update. Thanks @Lite3000!
