### ISSUE TITLE
Azerbaijani Translation

### ISSUE THREAD

**Issue by orkhan-huseyn** [iliakan/javascript-tutorial-en#714]
Please, add my name to the list.
I have just started to translate.

https://github.com/orkhan-huseyn/javascript-tutorial-az

**Comment by iliakan** [comment]
Ok, normally I add translations after several articles are done. 
To make sure it's something real, and to show non-zero percentage.

**Comment by orkhan-huseyn** [comment]
@iliakan i have three articles ready

**Comment by iliakan** [comment]
Ok, adding it to the list.

**Comment by iliakan** [comment]
Go on! :)

**Comment by ziyaddin** [comment]
@iliakan we are returning back to translations with our [community](https://github.com/bakujsdevs). 

Could you create a repo with language code `az`?

**Comment by iliakan** [comment]
@ziyaddin maintainers nicks and emails please?

**Comment by ziyaddin** [comment]
Maintainer 1:
Nick: @ziyaddin 
Email: in my bio

Maintainer 2:
Nick: @orkhan-huseyn 
Email: in his bio

**Comment by iliakan** [comment]
Created! Got an invitation?

**Comment by ziyaddin** [comment]
Yes. Thank you!
