### ISSUE TITLE
More precise wording when using string as function

### ISSUE THREAD

**Issue by dagolinuxoid** [iliakan/javascript-tutorial-en#715]
'If the first argument is a string, then JavaScript creates a function from it.'
The statement a bit loose - according to it  `setTimeout('alert',1000,'arg')` would be display `arg`.
 'If the first argument is a string, then JavasScript creates a function (function wrapper) and puts
the string into the function body treating it like a source code (converting it into source code)'

So `setTimeout("alert('Hello')", 1000);` is equivalent to `setTimeout(function(){alert('Hello')}, 1000);`
At the other hand my assertion is kinda verbose and clunky - it's the reason I put it into issue (not made PR)
src: [setTemoutSection](https://javascript.info/settimeout-setinterval#settimeout)

**Comment by iliakan** [comment]
It's not exactly equivalent, I think the function is created in global scope.
Still, I believe the phrase is quite obvious ;)
