### ISSUE TITLE
line 104

### ISSUE THREAD

**Issue by SeanAldenFitzgerald** [iliakan/javascript-tutorial-en#72]
On line 104 is the following: "...don't let the visitor to interact..."

should either be "...don't let the visitor interact..."

or

"don't allow the visitor to interact."

**Comment by iliakan** [comment]
where is it? couldn't find :(

**Comment by leighlawhon** [comment]
looks to me like it was fixed: https://github.com/iliakan/javascript-tutorial-en/edit/master/1-js/02-first-steps/09-alert-prompt-confirm/article.md

**Comment by iliakan** [comment]
;)
