### ISSUE TITLE
Translation to PT-Br

### ISSUE THREAD

**Issue by joao2391** [iliakan/javascript-tutorial-en#739]
Hello!
Could you please add Portuguese (PT-BR) to the list? 
https://github.com/joao2391/javascript-tutorial-pt-br

**Comment by iliakan** [comment]
The repository is empty.

Please let me know after you translate at least some articles, to make sure that the translation is real :)

**Comment by iliakan** [comment]
When I look at Wikipedia, there's only pt.wikipedia.org.

Does it really make sense to have separate pt-br.javascript.info and pt-pt.javascript.info? Or we can join the efforts to have just pt.javascript.info?

**Comment by iliakan** [comment]
@joao2391
