### ISSUE TITLE
Safari 12.0.2 returns null if prompt canceled

### ISSUE THREAD

**Issue by nrsmsf** [iliakan/javascript-tutorial-en#763]
it is not true
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24758182/51803469-98f96300-2266-11e9-9547-6ae02184d853.png">

**Comment by iliakan** [comment]
Please use English here.  What's exactly wrong?
Also, the Russian version may be slightly outdated =)

**Comment by nrsmsf** [comment]
if user click "Cancel" in prompt, Safari returns null, but in this book writed that it returns empty string.

**Comment by iliakan** [comment]
In English or Russian book?

**Comment by nrsmsf** [comment]
Russian, surely.

**Comment by iliakan** [comment]
Sorry, this repo is about English version. It's newer.
