### ISSUE TITLE
May I use some of your content in my blog?

### ISSUE THREAD

**Issue by YongzeYao** [iliakan/javascript-tutorial-en#764]
Hi Ilya,

Thank you for such great information! I have learned a lot from your site. 
Right now I am building a blog site (in Chinese) of my own, and wanna use some of your content 
(like pictures, code and arguments). Is it ok to do so? 
You could think of it as translating some parts of your content.
I will cite your site's URL for sure.

Thank you!

**Comment by iliakan** [comment]
The license is CC-BY-NC-SA. It means, you can freely use it non-commercially (without placing ads etc) while giving a reference to this website.
Also please see http://zh.javascript.info/.
