### ISSUE TITLE
Incorrect Tutorial Information 

### ISSUE THREAD

**Issue by Vedaz** [iliakan/javascript-tutorial-en#77]
In [https://javascript.info/function-expressions-arrows#function-declaration-in-a-block](https://javascript.info/function-expressions-arrows#function-declaration-in-a-block)
Function declared inside if's body block can execute outside without any problems. Only functions declared inside as variables are not visible outside.
Tested on 

- Firefox 54.0.1 x64 
- Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Other(clearer) test example [https://gist.github.com/Vedaz/335fdf79bfbd39ff86922f96152f8e5f](https://gist.github.com/Vedaz/335fdf79bfbd39ff86922f96152f8e5f)

**Comment by morajabi** [comment]
You did not get the point of the tutorial. The point is if a function is declared inside a block which won't be executed, then the function itself won't be created.

```
let age = 16; // take 16 as an example

if (age < 18) {
  welcome();               // \   (runs)
                           //  |
  function welcome() {     //  |
    alert("Hello!");       //  |  Function Declaration is available
  }                        //  |  everywhere in the block where it's declared
                           //  |
  welcome();               // /   (runs)

} else {
                           // \
  function welcome() {     //  |
    alert("Greetings!");   //  |  if age=16, the the execution does not go here,
  }                        //  |  so this "welcome" is never created
                           // /
}

// Here we're out of figure brackets,
// so we can not see Function Declarations made inside of them.

welcome(); // Error: welcome is not defined
```

**Comment by Vedaz** [comment]
> When Function Declaration is made within a code block, it is visible everywhere **inside that block. But not outside of it**.

> The Function Declaration is visible only inside the code block where it resides.

The tutorial did NOT make it clear that what you have explained (Thanks for clarifying though) is the case.
In addition to that there is a difference in behavior between variable/expression functions and declaration functions. Declaration functions are visible outside if the code executed once, while variable expression functions are not visible even if the code executed.

**Comment by iliakan** [comment]
`use strict` must be at the top of your script, not in the *separate* script, please fix it, and the results will change.
