### ISSUE TITLE
modules ?

### ISSUE THREAD

**Issue by parmentelat** [iliakan/javascript-tutorial-en#773]
Hi folks

After reading quite a few articles here and there about modularity in ECMAScript 6, I was trying to play around with this module / import / export business, and came to javascript.info with the hope to find some material on the matter; however, unless I missed it there does not seem to be anything (yet ?)

It feels like the topic is still in the oven or just cooling down :) so my understanding is you may be waiting for the matter to settle a bit ? Regardless, can you shed some light on your plans in this area ?

Anyways: thanks for the great resource, really cool :)

**Comment by avinash2wards** [comment]
Hello,

I was also searching for JavaScript modules (import & export) article on this site, could not find it.
Any plan to publish it?

**Comment by iliakan** [comment]
yes, soon

**Comment by iliakan** [comment]
done.

**Comment by parmentelat** [comment]
awesome, THANK YOU
