### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by mehradsadeghi** [iliakan/javascript-tutorial-en#793]
Hi @iliakan 
Hope you doing well.
I contacted you long time ago about translating JavaScript tutorials to Persian.

Its possible for me now to do the work. 
The process of translation may take lots of time as I'm alone right now.
I try to join other passionate translators. 

[https://github.com/mehradsadeghi/javascript-tutorial-fa](url)

Thanks,
Mehrad

**Comment by iliakan** [comment]
Great 👍 Let me know when some articles are translated, I'll add it to Readme.

**Comment by mehradsadeghi** [comment]
Sure. 
Thanks.

**Comment by iliakan** [comment]
The translation is in the official list, so closing this.
