### ISSUE TITLE
Bangla Translation

### ISSUE THREAD

**Issue by NilSagor** [iliakan/javascript-tutorial-en#822]
Bangla(Bangladesh) Translation

**Comment by iliakan** [comment]
Go ahead? :)

**Comment by NilSagor** [comment]
Hi, 
I'm learning javascript in very slowly from your site and trying to understand it.  
And translating is too slower than learning.
https://github.com/NilSagor/javascript-tutorial-bn

**Comment by iliakan** [comment]
Don't see much progress, closing the issue.
