### ISSUE TITLE
Typo in Export& Import

### ISSUE THREAD

**Issue by Lauviah0622** [iliakan/javascript-tutorial-en#860]
Excuse Me, I find a little typo in [https://javascript.info/import-export](url)
![未命名](https://user-images.githubusercontent.com/43416399/54593849-61d74f00-4a6a-11e9-81bb-8be99dbf2e6b.png)
I think the word miss letter "`t`" is `perfectly`.
Not a big problem. Thanks for your tutorial, that help me so much.

**Comment by sanchitbansal10** [comment]
I checked. It's fixed now. Can close this Issue
