### ISSUE TITLE
Typo in Microtasks and event loop

### ISSUE THREAD

**Issue by YongzeYao** [iliakan/javascript-tutorial-en#864]
![image](https://user-images.githubusercontent.com/22460339/54663792-a8936c00-4a9f-11e9-9e08-f422814961f0.png)
![image](https://user-images.githubusercontent.com/22460339/54663887-f6a86f80-4a9f-11e9-8874-d4f5a3653a4b.png)
Hey, Ilan, I think you made a typo here, it should be Promise.resolve().

**Comment by sanchitbansal10** [comment]
I checked. It's fixed. Can close this issue
