### ISSUE TITLE
Regarding cookie's expires option

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [iliakan/javascript-tutorial-en#881]
In this [article.md](https://github.com/iliakan/javascript-tutorial-en/blob/7f4040a8c27dc32a1f74727fbb66aa8285ea85fb/2-ui/5-data-storage/01-cookie/article.md), there is a sentence and an example like below.

```
If we set expires to a date in the past, the cookie is deleted.

max-age=3600
```

Is it the right option value? I might be missing something because I'm not a server-side expert. So, I wonder it is.

**Comment by iliakan** [comment]
`max-age` is number in seconds for the cookie to live.

What confuses you?

**Comment by Violet-Bora-Lee** [comment]
if the seconds in 3,600, it didnt represent a date in the past. isnt it?

**Comment by iliakan** [comment]
Yes, but this sentence relates to the previous paragraph.

max-age is the next option.

**Comment by Violet-Bora-Lee** [comment]
oh i see lol.
I confused as i usually see docs on Markdown editor
Thanks
