### ISSUE TITLE
Translation request for Marathi (mr) and Hindi (hi)

### ISSUE THREAD

**Issue by maheshwaghmare** [iliakan/javascript-tutorial-en#883]
Hello,

I have forked the repo for `Marathi (mr)` and `Hindi (hi)` languages. I'll create a PR soon.

Repositories URLs are below:
- https://github.com/maheshwaghmare/javascript-tutorial-mr
- https://github.com/maheshwaghmare/javascript-tutorial-hi

**Comment by iliakan** [comment]
Please take a look at https://github.com/iliakan/javascript-tutorial-en/issues/641

Now sure how the translation is going, contact the author there ;)

I'd suggest to do only one language at a time.

**Comment by iliakan** [comment]
Let me know what you decide.

**Comment by siradityaverma** [comment]
@maheshwaghmare Would love to work together on the Hindi translation. Wanna join?

**Comment by iliakan** [comment]
@siradityaverma I made an issue on your repo about transfering it ;)
