### ISSUE TITLE
508 section for event.preventDefault

### ISSUE THREAD

**Issue by leighlawhon** [iliakan/javascript-tutorial-en#90]
Without changing what you have, I would put a note about how preventing the default behavior of an anchor or submit button changes its intention and is therefore, no longer semantic and 508 compliant. So, anchors navigate to parts of pages or external pages, buttons perform actions and submit buttons submit forms. If you are doing anything else with these elements you should consider using another element.

**Comment by iliakan** [comment]
That would be a nice note. People should keep the semantical meaning of the elements even if they add JS.

Could you make a PR with that?

**Comment by iliakan** [comment]
Added a warning at the bottom.
